/* Hyper's own generated DOM structure and attribute contract that this
   plugin hooks into (or asks Hyper's built-in CSS to expose), plus this
   plugin's own class/attribute names that get created in one place and
   queried or toggled in another. Centralized here so those strings never
   drift out of sync between files. */

export const SELECTORS = {
  headerHeader: '.header_header',
  hyperMain: '.hyper_main',
  tab: '.tab_tab',
  tabIcon: '.tab_icon',
  tabsTitle: '.tabs_title',
  tabsList: '.tabs_list',
  terminalTextarea: '.terminal textarea',
} as const;

export const CLASSES = {
  tabActive: 'tab_active',
  tabCwd: 'kit-tab-cwd',
  tabPanes: 'kit-tab-panes',
  tabAgents: 'kit-tab-agents',
  tabAgentIcon: 'kit-tab-agent',
  tabAgentMask: 'kit-tab-agent-mask',
  tabAgentMore: 'kit-tab-agent-more',
  dragging: 'kit-tab-dragging',
  singleTab: 'kit-tab-single',
  tabDragGhost: 'kit-tab-drag-ghost',
  tabDropIndicator: 'kit-tab-drop-indicator',
  closeConfirm: 'kit-close-confirm',
  closeConfirmCard: 'kit-close-confirm-card',
  closeConfirmTitle: 'kit-close-confirm-title',
  closeConfirmBody: 'kit-close-confirm-body',
  closeConfirmActions: 'kit-close-confirm-actions',
  closeConfirmCancel: 'kit-close-confirm-cancel',
  closeConfirmDanger: 'kit-close-confirm-danger',
  /* agent monitor popups (opencode permission / question cards) */
  agentMonitor: 'kit-amon',
  agentMonitorBackdrop: 'kit-amon-backdrop',
  agentMonitorClosing: 'kit-amon-closing',
  agentMonitorCard: 'kit-amon-card',
  agentMonitorHeader: 'kit-amon-header',
  agentMonitorIcon: 'kit-amon-icon',
  agentMonitorTitleCol: 'kit-amon-title-col',
  agentMonitorTitle: 'kit-amon-title',
  agentMonitorSub: 'kit-amon-sub',
  agentMonitorBody: 'kit-amon-body',
  agentMonitorPattern: 'kit-amon-pattern',
  agentMonitorPatternMore: 'kit-amon-pattern-more',
  agentMonitorMetaRow: 'kit-amon-meta-row',
  agentMonitorMetaLabel: 'kit-amon-meta-label',
  agentMonitorMetaValue: 'kit-amon-meta-value',
  agentMonitorDetailsToggle: 'kit-amon-details-toggle',
  agentMonitorMeta: 'kit-amon-meta',
  agentMonitorInput: 'kit-amon-input',
  agentMonitorActions: 'kit-amon-actions',
  agentMonitorChips: 'kit-amon-chips',
  agentMonitorPrimary: 'kit-amon-primary',
  agentMonitorSecondary: 'kit-amon-secondary',
  agentMonitorDanger: 'kit-amon-danger',
  agentMonitorView: 'kit-amon-view',
  agentMonitorStatus: 'kit-amon-status',
  agentMonitorStatusError: 'kit-amon-status-error',
  agentMonitorChip: 'kit-amon-chip',
  agentMonitorChipOn: 'kit-amon-chip-on',
  agentMonitorQuestion: 'kit-amon-question',
  agentMonitorRiskLow: 'kit-amon-risk-low',
  agentMonitorRiskMedium: 'kit-amon-risk-medium',
  agentMonitorRiskHigh: 'kit-amon-risk-high',
  agentMonitorFooter: 'kit-amon-footer',
  agentMonitorDivider: 'kit-amon-divider',
  agentMonitorDividerDot: 'kit-amon-divider-dot',
  agentMonitorFooterRow: 'kit-amon-footer-row',
  agentMonitorAgent: 'kit-amon-agent',
  agentMonitorAgentIcon: 'kit-amon-agent-icon',
  agentMonitorAgentMask: 'kit-amon-agent-mask',
  agentMonitorAgentName: 'kit-amon-agent-name',
  /* explorer popover (whole-disk directory tree) */
  explorerPopover: 'kit-explorer',
  explorerHeader: 'kit-explorer-header',
  explorerTitle: 'kit-explorer-title',
  explorerClose: 'kit-explorer-close',
  explorerBody: 'kit-explorer-body',
  explorerRow: 'kit-explorer-row',
  explorerRowMain: 'kit-explorer-row-main',
  explorerChevron: 'kit-explorer-chevron',
  explorerChevronOpen: 'kit-explorer-chevron-open',
  explorerIcon: 'kit-explorer-icon',
  explorerName: 'kit-explorer-name',
  explorerPin: 'kit-explorer-pin',
  explorerPinActive: 'kit-explorer-pin-active',
  explorerTerminal: 'kit-explorer-terminal',
  explorerFiles: 'kit-explorer-files',
  explorerSplit: 'kit-explorer-split',
  explorerChildren: 'kit-explorer-children',
  explorerEmpty: 'kit-explorer-empty',
  explorerLoading: 'kit-explorer-loading',
  explorerError: 'kit-explorer-error',
  explorerHeaderActions: 'kit-explorer-header-actions',
  explorerToggleFullTree: 'kit-explorer-toggle-fulltree',
  explorerToggleHidden: 'kit-explorer-toggle-hidden',
  explorerToggleOn: 'kit-explorer-toggle-on',
  /* bookmark popover (saved folder grid) */
  bookmarkPopover: 'kit-bookmark',
  bookmarkHeader: 'kit-bookmark-header',
  bookmarkTitle: 'kit-bookmark-title',
  bookmarkClose: 'kit-bookmark-close',
  bookmarkHeaderActions: 'kit-bookmark-header-actions',
  bookmarkBody: 'kit-bookmark-body',
  bookmarkGrid: 'kit-bookmark-grid',
  bookmarkTile: 'kit-bookmark-tile',
  bookmarkTileMain: 'kit-bookmark-tile-main',
  bookmarkTileIcon: 'kit-bookmark-tile-icon',
  bookmarkTileName: 'kit-bookmark-tile-name',
  bookmarkTilePath: 'kit-bookmark-tile-path',
  bookmarkTilePathInner: 'kit-bookmark-tile-path-inner',
  bookmarkTileRemove: 'kit-bookmark-tile-remove',
  bookmarkTileActions: 'kit-bookmark-tile-actions',
  bookmarkTileAction: 'kit-bookmark-tile-action',
  bookmarkEmpty: 'kit-bookmark-empty',
} as const;

export const ATTRIBUTES = {
  tabbarResize: 'data-kit-tab-resize',
  envPanel: 'data-kit-tab-env-panel',
  bottomPanel: 'data-kit-tab-bottom-panel',
  topPanel: 'data-kit-tab-top-panel',
  mediaPanel: 'data-kit-tab-media-panel',
} as const;
